"""Adding few tables

Revision ID: 160772f75a45
Revises: 4140a3b14bdc
Create Date: 2022-06-07 02:40:37.997036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160772f75a45'
down_revision = '4140a3b14bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requested_events',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(length=200), nullable=False),
    sa.Column('EventPrize', sa.String(length=200), nullable=False),
    sa.Column('EventDateTime', sa.DateTime(), nullable=True),
    sa.Column('EventVenue', sa.String(length=200), nullable=False),
    sa.Column('EventRules', sa.String(length=500), nullable=False),
    sa.Column('EventType', sa.String(length=100), nullable=False),
    sa.Column('EventContact', sa.String(length=100), nullable=False),
    sa.Column('OrganizerId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requested_events')
    # ### end Alembic commands ###
