"""Taking out time

Revision ID: 18027e6cf3f8
Revises: ae9fc57070ae
Create Date: 2022-06-07 07:01:33.593092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18027e6cf3f8'
down_revision = 'ae9fc57070ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Pid', table_name='TugOfWar')
    op.drop_table('TugOfWar')
    op.drop_index('Pid', table_name='CodingCrazy')
    op.drop_table('CodingCrazy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CodingCrazy',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('Pid', 'CodingCrazy', ['Pid'], unique=False)
    op.create_table('TugOfWar',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('Pid', 'TugOfWar', ['Pid'], unique=False)
    # ### end Alembic commands ###
