"""Added organizer table

Revision ID: 4140a3b14bdc
Revises: 6f4f64da6a53
Create Date: 2022-06-07 02:00:45.279031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4140a3b14bdc'
down_revision = '6f4f64da6a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('EventId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizer')
    # ### end Alembic commands ###
