"""Added events table

Revision ID: 6f4f64da6a53
Revises: d1e923723603
Create Date: 2022-06-05 15:34:06.274564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4f64da6a53'
down_revision = 'd1e923723603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(length=200), nullable=False),
    sa.Column('EventPrize', sa.String(length=200), nullable=False),
    sa.Column('EventDateTime', sa.DateTime(), nullable=True),
    sa.Column('EventVenue', sa.String(length=200), nullable=False),
    sa.Column('EventRules', sa.String(length=500), nullable=False),
    sa.Column('EventType', sa.String(length=100), nullable=False),
    sa.Column('EventContact', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
