"""4rd Migration

Revision ID: c05fbc927572
Revises: 
Create Date: 2022-06-02 19:19:03.216747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05fbc927572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=200), nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.Column('PasswordHashed', sa.String(length=300), nullable=False),
    sa.Column('Phone', sa.String(length=12), nullable=True),
    sa.Column('UserType', sa.String(length=10), nullable=True),
    sa.Column('Date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
